ItsJonQ/g2

- jest.config.js
- packages/components/jest.config.js
- packages/components/src/Alert/__tests__/__snapshots__/Alert.test.js.snap
- packages/components/src/Button/__tests__/__snapshots__/Button.test.js.snap
- packages/components/src/ControlGroup/__tests__/__snapshots__/ControlGroup.test.js.snap
- packages/components/src/Flex/Flex.js
- packages/components/src/Flex/__tests__/__snapshots__/Flex.test.js.snap
- packages/components/src/FormGroup/__tests__/__snapshots__/FormGroup.test.js.snap
- packages/components/src/Grid/Grid.js
- packages/components/src/Grid/__tests__/__snapshots__/Grid.test.js.snap
- packages/components/src/HStack/__tests__/__snapshots__/HStack.test.js.snap
- packages/components/src/Panel/__tests__/__snapshots__/Panel.test.js.snap
- packages/components/src/SearchInput/__tests__/__snapshots__/SearchInput.test.js.snap
- packages/components/src/Select/__tests__/__snapshots__/Select.test.js.snap
- packages/components/src/Stepper/__tests__/__snapshots__/Stepper.test.js.snap
- packages/components/src/TextInput/__tests__/__snapshots__/TextField.test.js.snap
- packages/components/src/VStack/__tests__/__snapshots__/VStack.test.js.snap
- packages/components/src/__fixtures__/components/Sidebar.js
- packages/components/src/__stories__/WIP/GlobalStylesSidebar.stories.js
- packages/components/src/__stories__/WIP/UserProfilesPlugin.stories.js
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/styles/jest.config.js
- packages/styles/src/__tests__/css.test.js
- packages/styles/src/css.js
- packages/styles/src/style-system.js
This update adds scale value handling for the `css` function within the `@wp-g2/styles` package. The implementation is inspired by how Theme UI handles scaled values. However, G2's implementation is more focused, mostly for margin/padding/grid/flex based values.
`Grid`  component implementations of `gap` (e.g. `<Grid gap={28} />`)  will break. Previously, Grid's `gap` used the value directly, without taking into consideration the Style system's grid system. This led to some confusion as components like `<Space />` and `<HStack />` used the grid system for values.
**Before**
```jsx
<Grid gap={28} />
```
**After**
```jsx
<Grid gap={8} />
```
This was observed by @sixhours and @ItsJonQ .
> Styles: Add scale value compiling

- .storybook/preview.js
- packages/components/src/Card/Card.js
- packages/components/src/Card/Card.styles.js
- packages/components/src/Card/__tests__/__snapshots__/Card.test.js.snap
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/styles/src/theme/config.js
This update adds a design token for `Card` components, specifically `cardBorderRadius`. This allows Card borders to be adjusted via `ThemeProvider` (or CSS variables)
> Card: Add border-radius design token

- packages/create-styles/src/components/ThemeProvider/ThemeProvider.js
- packages/create-styles/src/components/ThemeProvider/ThemeProvider.utils.js
- packages/create-styles/src/createStyleSystem/createStyleSystem.js
- packages/create-styles/src/index.js
- packages/styles/src/components/ThemeProvider.js
- packages/styles/src/system.js
This update enhances the `ThemeProvider` from the `create-styles` package to use a custom `ThemeProvider` enhanced with a `injectGlobal` flow from the custom Emotion instance.
This enables `ThemeProvider` to be compatible with Emotion's SSR flow.
Resolves: https://github.com/ItsJonQ/g2/issues/48
> Create Styles: ThemeProvider - Inject global on initial render

- packages/context/src/__tests__/ComponentsProvider.test.js
- packages/context/src/__tests__/__snapshots__/ComponentsProvider.test.js.snap
- packages/context/src/connect.js
This update adds a special prop (`_overrides`) for props being passed to connected components within the Context system. `_overrides` allows for the `ComponentsProvider` to override incoming props from the connected component, similar to the workflow for `!important` in CSS.
**Example**
```jsx
<ComponentsProvider
value={{
Text: {
_overrides: {
numberOfLines: 2
}
}
}}
/>
```
Resolves: https://github.com/ItsJonQ/g2/issues/31
> Context: Add ability to override connected components

- packages/create-styles/src/components/ThemeProvider/ThemeProvider.js
- packages/create-styles/src/components/ThemeProvider/ThemeProvider.utils.js
- packages/create-styles/src/createStyleSystem/createCoreElement.js
- packages/create-styles/src/createStyleSystem/createStyleSystem.js
- packages/create-styles/src/hooks/useHydrateGlobalStyles.js
This update improves the ThemeProvider initial (theme) style rendering. The
change needed to achieve this involved coordinating the injectGlobal function
call in the ThemeProvider generated from the createStyleSystem factory.
The initial injectGlobal is the same as a coreElement, using the
useHydrateGlobalStyles hook.
Ultimately, this helps with SSR rendering for custom theme styles.
> Create Styles: Improve ThemeProvider initial (theme) style rendering

- .storybook/themes/blueberry.js
- packages/create-styles/src/components/ThemeProvider/ThemeProvider.js
- packages/create-styles/src/components/ThemeProvider/ThemeProvider.utils.js
- packages/create-styles/src/createStyleSystem/createStyleSystem.js
- packages/create-styles/src/createStyleSystem/utils.js
Checkout the branch locally and pass `darkTheme`, `highContrastTheme` and `darkHighContrastTheme` to the `ThemeProvider` in `.storybook/preview.js`. Pass some different variables and ensure they're being applied correctly with the expected specificity.
> Add dark and high contrast theme support to ThemeProvider

- packages/components/src/BaseModal/BaseModal.js
- packages/components/src/Modal/__stories__/Modal.stories.js
- packages/components/src/Modal/index.js
- packages/components/src/Modal/useModalState.js
Run storybook and visit the controlled modal example and ensure both buttons cause the modal to open and that focus is returned to them. Likewise, open the default modal example and ensure it still behaves as expected.
Closes https://github.com/ItsJonQ/g2/issues/29
> Add controlled modal example

- packages/components/src/UnitInput/index.d.ts
- packages/utils/src/unitValues.js
This update improves the CSS prop validation util function that's used in `UnitInput`. This fix allows for values like `calc()`, `var()`, and other native CSS functions.
* Run `yarn start` to fire up Storybook
* Go to the [UnitInput story](http://localhost:6006/iframe.html?id=components-unitinput--default)
* Add whatever (valid) `calc()` value to one of the inputs. Example `calc(1px + 2px)`
Resolves: https://github.com/ItsJonQ/g2/issues/76
> UnitInput: Improve cssProp validation to allow for values like calc()

- packages/components/src/Select/Select.js
- packages/components/src/Select/Select.styles.js
- packages/components/src/Select/Select.utils.js
- packages/components/src/Select/SelectArrow.js
- packages/components/src/Select/__stories__/Select.stories.js
- packages/components/src/Select/__tests__/__snapshots__/Select.test.js.snap
- packages/components/src/Select/useSelect.js
- packages/components/src/TextInput/__stories__/TextInput.stories.js
- packages/components/types/components/Select.d.ts
- packages/utils/types/index.d.ts
This update enhances the `Select` component to support grouping (when passing in values via the `options` prop), `placeholder` rendering, and multi-select via the `multiple` attribute.
In addition to adding these features, `Select` was featured to use the hook-based rendering approach (via `useSelect`). Type definitions have also been updated.
A "placeholder" UI can be rendered by providing a `placeholder` (`string`) value.
Automatic `optgroup` rendering can be done by providing `Select` with `options` that look like this:
```js
const options = [
{
label: 'Frozen',
options: [
{
label: 'Frozen Heart',
value: 'frozen-heart',
},
{
label: 'Do You Want To Build A Snowman?',
value: 'do-you-want-to-build-a-snowman',
},
{
label: 'First Time In Forever',
value: 'first-time-in-forever',
},
],
},
{ …
```
> Select: Add option grouping, placeholder, and multiple support

- packages/utils/src/is.js
Refactors the internal `is` library to basically re-export some lodash functions with a few extras based on https://github.com/ItsJonQ/is
Ensure all existing components continue to work.
Closes https://github.com/ItsJonQ/g2/issues/91
> Refactor `is` using `lodash`

- packages/components/src/ExternalLink/ExternalLink.js
- packages/components/src/ExternalLink/ExternalLink.styles.js
- packages/components/src/ExternalLink/__stories__/ExternalLink.stories.js
- packages/components/src/ExternalLink/__tests__/ExternalLink.test.js
- packages/components/src/ExternalLink/__tests__/__snapshots__/ExternalLink.test.js.snap
- packages/components/src/ExternalLink/index.js
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/components/src/index.js
Adds a new `ExternalLink` component in parity with `@wordpress/components/ExternalLink`.
> Components: ExternalLink

- packages/components/src/Button/Button.styles.js
- packages/components/src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
- packages/components/src/ColorControl/__tests__/__snapshots__/ColorControl.test.js.snap
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/styles/src/theme/config.js
- packages/styles/src/theme/darkModeConfig.js
This update improves the focus ring visibility for the `subtle control` variant of `Button`.
The styles are adjusted to closely match the current implementation within Gutenberg.
GIF demo
The updates involved adding new Theme `config` variables.
At the moment, all focus ring shadows are handled by adding a `0.5px` (config specified) `box-shadow` on the **outside** of the control. For `Button` components in a segmented `ButtonGroup` cluster, we can see a `0.5px` size difference between the borders.
(Zoomed in screenshot)
If this isn't ideal, we can add some adjustments in the config.
---
Resolves https://github.com/ItsJonQ/g2/issues/108
> Button: Update focus ring rendering for subtle * control variant

- packages/components/src/Alert/__tests__/__snapshots__/Alert.test.js.snap
- packages/components/src/BaseButton/__tests__/__snapshots__/BaseButton.test.js.snap
- packages/components/src/BaseField/__tests__/__snapshots__/BaseField.test.js.snap
- packages/components/src/BlankSlate/__tests__/__snapshots__/BlankSlate.test.js.snap
- packages/components/src/Button/__tests__/__snapshots__/Button.test.js.snap
- packages/components/src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
- packages/components/src/Card/__tests__/__snapshots__/Card.test.js.snap
- packages/components/src/ClipboardButton/__tests__/__snapshots__/ClipboardButton.test.js.snap
- packages/components/src/CloseButton/__tests__/__snapshots__/CloseButton.test.js.snap
- packages/components/src/Collapsible/__tests__/__snapshots__/Collapsible.test.js.snap
- packages/components/src/ColorControl/__tests__/__snapshots__/ColorControl.test.js.snap
- packages/components/src/ControlGroup/__tests__/__snapshots__/ControlGroup.test.js.snap
- packages/components/src/Flex/__tests__/__snapshots__/Flex.test.js.snap
- packages/components/src/Flex/useFlex.js
- packages/components/src/FormGroup/__tests__/__snapshots__/FormGroup.test.js.snap
- packages/components/src/HStack/__tests__/__snapshots__/HStack.test.js.snap
- packages/components/src/ListGroup/__tests__/__snapshots__/ListGroup.test.js.snap
- packages/components/src/Popover/__tests__/__snapshots__/Popover.test.js.snap
- packages/components/src/SearchInput/__tests__/__snapshots__/SearchInput.test.js.snap
- packages/components/src/Select/__tests__/__snapshots__/Select.test.js.snap
- packages/components/src/Stepper/__tests__/__snapshots__/Stepper.test.js.snap
- packages/components/src/Tag/__tests__/__snapshots__/Tag.test.js.snap
- packages/components/src/TextField/__tests__/__snapshots__/TextField.test.js.snap
- packages/components/src/TextInput/__tests__/__snapshots__/TextField.test.js.snap
- packages/components/src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
- packages/components/src/VStack/__tests__/__snapshots__/VStack.test.js.snap
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
The issue is the `> * + *` based rule isn't specific enough to target children that may have `margin: 0` rules.
This is because the CSS universal selector (`*`) has a specificity rating of zero. Compounding it like `* + *` doesn't change this.
As a work around... we can do something like this:
```css
> * + *:not(marquee) {
}
```
The `:not()` will bump it's specificity rating. And there's a 99.9999999999999999999% guarantee that the element would not be a `marquee` within the context of React + modern web UI.
Here's a screenshot of this solution working:
---
Resolves:
https://github.com/ItsJonQ/g2/issues/119
> Flex: Fix style rendering for child items

- packages/components/src/TextInput/TextInput.styles.js
- packages/components/src/UnitInput/UnitInput.js
- packages/components/src/UnitInput/UnitInput.styles.js
- packages/components/src/UnitInput/UnitInputSelect.js
This update fixes the inner stepper / unit controls for `TextInput` and `UnitInput` for their disabled state.
These inner controls are no longer tabbable and cannot be interacted with.
Resolves https://github.com/ItsJonQ/g2/issues/107
> TextInput/UnitInput: Fix disabled handling for suffix controls

- packages/components/src/Slider/__stories__/Slider.stories.js
- packages/components/src/Slider/__tests__/Slider.test.js
- packages/components/src/Slider/__tests__/__snapshots__/Slider.test.js.snap
- packages/components/src/Slider/useSlider.js
- packages/design-tools/src/__stories__/Presentation/shared.js
This update adds built-in unit handling support for `Slider`. `Slider` now knows how to understand incoming unit values (e.g. `50px`). It also knows how to preserve unit values during an `onChange` event.
For example:
```jsx
const [value, setValue] = useState('50px')
<Slider value={value} onChange={setValue} />
```
The `Slider` will parse and pass the value of `50` to the internal `input`.
During a change, say to a value of `49`, the `onChange` callback will be `49px`. This is because `Slider` accounts for a potential unit passed in via the `value` prop.
`Slider` also knows how to account for situations where the value may change 👍 
Resolves https://github.com/ItsJonQ/g2/issues/109
> Slider: Add support for unit handling

- packages/components/src/Alert/__tests__/__snapshots__/Alert.test.js.snap
- packages/components/src/ArrowIndicator/__tests__/__snapshots__/ArrowIndicator.test.js.snap
- packages/components/src/BaseButton/BaseButton.styles.js
- packages/components/src/BaseButton/__tests__/__snapshots__/BaseButton.test.js.snap
- packages/components/src/BlankSlate/__tests__/__snapshots__/BlankSlate.test.js.snap
- packages/components/src/Button/__tests__/__snapshots__/Button.test.js.snap
- packages/components/src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
- packages/components/src/Card/__tests__/__snapshots__/Card.test.js.snap
- packages/components/src/ClipboardButton/__tests__/__snapshots__/ClipboardButton.test.js.snap
- packages/components/src/CloseButton/__tests__/__snapshots__/CloseButton.test.js.snap
- packages/components/src/Collapsible/__tests__/__snapshots__/Collapsible.test.js.snap
- packages/components/src/ColorCircle/__tests__/__snapshots__/ColorCircle.test.js.snap
- packages/components/src/ColorControl/__tests__/__snapshots__/ColorControl.test.js.snap
- packages/components/src/ControlGroup/__tests__/__snapshots__/ControlGroup.test.js.snap
- packages/components/src/ExternalLink/__tests__/__snapshots__/ExternalLink.test.js.snap
- packages/components/src/HelpTip/HelpTip.js
- packages/components/src/HelpTip/__tests__/__snapshots__/HelpTip.test.js.snap
- packages/components/src/Icon/Icon.js
- packages/components/src/Icon/__tests__/__snapshots__/Icon.test.js.snap
- packages/components/src/Popover/__tests__/__snapshots__/Popover.test.js.snap
- packages/components/src/SearchInput/__tests__/__snapshots__/SearchInput.test.js.snap
- packages/components/src/Select/__tests__/__snapshots__/Select.test.js.snap
- packages/components/src/Stepper/__tests__/__snapshots__/Stepper.test.js.snap
- packages/components/src/Tag/__tests__/__snapshots__/Tag.test.js.snap
- packages/components/src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
This update improves how the `Icon` component handles the `fill` rendering for `@wordpress/icons` svgs. 
This idea came from the recent `Icon` component + package refactor,
https://github.com/ItsJonQ/g2/pull/133/files/eb4a8c7ff3e643569bd26a2f62516c9ea99258e3#r525559793
Because `@wordpress/components` uses `fill` for it's Icon colors (vs. `color` from `react-icons`), we needed to add the `fill` CSS property to various styles (e.g. `BaseButton`) to accommodate this.
I can imagine this not scaling well, as components (G2 or not) may need to adjust icon color from a higher node vs. direct manipulation through `<Icon fill="red" />`. In the case of `Button`, by default, we want the `Icon` to absorb the (text) color from the `Button`.
I think we can do this for `Icon.js`
```jsx
sx.fill = css({ …
```
> Icon: Improve "fill" color rendering

- packages/components/src/Alert/__tests__/__snapshots__/Alert.test.js.snap
- packages/components/src/BaseButton/BaseButton.styles.js
- packages/components/src/BaseButton/__tests__/__snapshots__/BaseButton.test.js.snap
- packages/components/src/BaseField/BaseField.styles.js
- packages/components/src/BaseField/__tests__/__snapshots__/BaseField.test.js.snap
- packages/components/src/Button/__tests__/__snapshots__/Button.test.js.snap
- packages/components/src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
- packages/components/src/Card/__tests__/__snapshots__/Card.test.js.snap
- packages/components/src/ClipboardButton/__tests__/__snapshots__/ClipboardButton.test.js.snap
- packages/components/src/CloseButton/__tests__/__snapshots__/CloseButton.test.js.snap
- packages/components/src/Collapsible/__tests__/__snapshots__/Collapsible.test.js.snap
- packages/components/src/ColorControl/__tests__/__snapshots__/ColorControl.test.js.snap
- packages/components/src/ControlGroup/ControlGroupItem.styles.js
- packages/components/src/ControlGroup/__tests__/__snapshots__/ControlGroup.test.js.snap
- packages/components/src/FormGroup/__tests__/__snapshots__/FormGroup.test.js.snap
- packages/components/src/Popover/__tests__/__snapshots__/Popover.test.js.snap
- packages/components/src/SearchInput/__tests__/__snapshots__/SearchInput.test.js.snap
- packages/components/src/Select/__tests__/__snapshots__/Select.test.js.snap
- packages/components/src/Slider/Slider.styles.js
- packages/components/src/Slider/__tests__/__snapshots__/Slider.test.js.snap
- packages/components/src/Stepper/__tests__/__snapshots__/Stepper.test.js.snap
- packages/components/src/Tag/__tests__/__snapshots__/Tag.test.js.snap
- packages/components/src/TextInput/TextInput.styles.js
- packages/components/src/TextInput/__tests__/__snapshots__/TextField.test.js.snap
- packages/components/src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
This update fixes a strange rendering bug for Chrome relating to the sub-pixel (`0.5px`) `box-shadow` styles that render for control focus states.
This bug occurs when the control is rendered within a container with overflow handling (e.g. `overflow: hidden`).
It's very odd. It's caused by a combination of things... ultimately related to how Chrome renders "layers" (at least, that's what the debugging indicates).
The solution involved adjusting how `z-index` is handled for controls. It has been moved strictly to `ControlGroup`, relying on the `:focus-within` pseudo to elevated focused items within a `ControlGroup`. (`:focus-within` isn't supported on IE11, but I think it will be okay. The UI works, it's just the border won't be correctly layered).
The rollercoaster ride that is the …
> Controls: Fix inconsistent focus ring for Chrome

- packages/components/src/Alert/__tests__/__snapshots__/Alert.test.js.snap
- packages/components/src/BaseButton/__tests__/__snapshots__/BaseButton.test.js.snap
- packages/components/src/BaseField/__tests__/__snapshots__/BaseField.test.js.snap
- packages/components/src/BlankSlate/__tests__/__snapshots__/BlankSlate.test.js.snap
- packages/components/src/Button/__tests__/__snapshots__/Button.test.js.snap
- packages/components/src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
- packages/components/src/Card/__tests__/__snapshots__/Card.test.js.snap
- packages/components/src/ClipboardButton/__tests__/__snapshots__/ClipboardButton.test.js.snap
- packages/components/src/CloseButton/__tests__/__snapshots__/CloseButton.test.js.snap
- packages/components/src/Collapsible/__tests__/__snapshots__/Collapsible.test.js.snap
- packages/components/src/ColorControl/__tests__/__snapshots__/ColorControl.test.js.snap
- packages/components/src/ControlGroup/__tests__/__snapshots__/ControlGroup.test.js.snap
- packages/components/src/Flex/__tests__/__snapshots__/Flex.test.js.snap
- packages/components/src/Flex/useFlex.js
- packages/components/src/FormGroup/__tests__/__snapshots__/FormGroup.test.js.snap
- packages/components/src/HStack/__tests__/__snapshots__/HStack.test.js.snap
- packages/components/src/ListGroup/__tests__/__snapshots__/ListGroup.test.js.snap
- packages/components/src/Popover/__tests__/__snapshots__/Popover.test.js.snap
- packages/components/src/SearchInput/__tests__/__snapshots__/SearchInput.test.js.snap
- packages/components/src/Select/__tests__/__snapshots__/Select.test.js.snap
- packages/components/src/Stepper/__tests__/__snapshots__/Stepper.test.js.snap
- packages/components/src/Tag/__tests__/__snapshots__/Tag.test.js.snap
- packages/components/src/TextInput/__tests__/__snapshots__/TextField.test.js.snap
- packages/components/src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
- packages/components/src/VStack/__tests__/__snapshots__/VStack.test.js.snap
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
This update fixes the rendering stability for child elements rendered by `Flex` (and anything that uses `Flex`, such as `HStack`).
There is a strange `display: flex` bug where child elements without `min-width: 0`/`min-height: 0` may result in unexpected overflow issues, for example this example (below) in Firefox:
By default, this is handled by `FlexItem` and `FlexBlock`. Previously, `Flex` would automatically wrap children elements with `FlexItem` or `FlexBlock`. This was great for rendering stability. However, this added hundreds and hundreds of extra `DivHTMLElement` nodes in the DOM.
This update adds the `width`/`height` normalization by using a `> *` selector.
This shouldn't affect potential child styles as the universal `*` selector has a specificity score of `0`.
**Fixed** …
> Flex: Fix width/height adaptive size rendering stability

- packages/components/src/Dropdown/Dropdown.js
- packages/components/src/Dropdown/__stories__/Dropdown.stories.js
- packages/components/src/__stories__/WIP/ListGroups.stories.js
- packages/utils/src/react.js
This update improves the `Dropdown` component to accept a custom Reakit (menu) state. It also now accommodates render function handling from the `children` prop.
```jsx
<Dropdown visible>
{({ onClose }) => {
return (
<>
<DropdownTrigger>Dropdown</DropdownTrigger>
<DropdownMenu>
<DropdownMenuItem onClick={onClose}>
One
</DropdownMenuItem>
<DropdownMenuItem>Two</DropdownMenuItem>
<DropdownMenuItem>Three</DropdownMenuItem>
</DropdownMenu>
</>
);
}}
</Dropdown>
```
The callbacks props being passed to the `children` render prop is remapped (`useMenuState`) to support current `@wordpress/components` Dropdown/DropdownMenu APIs:
https://github.com/WordPress/gutenberg/tree/master/packages/components/src/dropdown-menu
---
Resolves: https://github.com/ItsJonQ/g2/issues/147
> Dropdown: Enable custom state and children render function handling

- lerna.json
- packages/components/package.json
- packages/components/src/Alert/__tests__/__snapshots__/Alert.test.js.snap
- packages/components/src/BaseButton/BaseButton.styles.js
- packages/components/src/BaseButton/__tests__/__snapshots__/BaseButton.test.js.snap
- packages/components/src/Button/__tests__/__snapshots__/Button.test.js.snap
- packages/components/src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
- packages/components/src/Card/__tests__/__snapshots__/Card.test.js.snap
- packages/components/src/ClipboardButton/__tests__/__snapshots__/ClipboardButton.test.js.snap
- packages/components/src/CloseButton/__tests__/__snapshots__/CloseButton.test.js.snap
- packages/components/src/Collapsible/__tests__/__snapshots__/Collapsible.test.js.snap
- packages/components/src/ColorControl/__tests__/__snapshots__/ColorControl.test.js.snap
- packages/components/src/ControlGroup/__tests__/__snapshots__/ControlGroup.test.js.snap
- packages/components/src/Popover/__tests__/__snapshots__/Popover.test.js.snap
- packages/components/src/SearchInput/__tests__/__snapshots__/SearchInput.test.js.snap
- packages/components/src/Stepper/__tests__/__snapshots__/Stepper.test.js.snap
- packages/components/src/Tag/__tests__/__snapshots__/Tag.test.js.snap
- packages/components/src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/components/src/font-size-control/font-size-control-utils.js
- packages/components/src/font-size-control/use-font-size-control.js
- packages/design-tools/package.json
- packages/hint/package.json
- packages/website/package.json
This update resolves the `FontSizeControl` component `onChange` handling (for custom items) for Gutenberg.
It also ensures that `Button` components render more consistently within the Gutenberg UI, using a `height` reset.
Resolves https://github.com/ItsJonQ/g2/issues/179
> FontSizeControl: Fix Button height + Custom value

- packages/components/src/font-size-control/__stories__/index.stories.js
- packages/components/src/select-dropdown/__stories__/index.stories.js
- packages/components/src/select-dropdown/select-dropdown-utils.js
- packages/components/src/select-dropdown/select-dropdown.js
- packages/components/src/select-dropdown/use-select-dropdown.js
This update adds the ability for `SelectDropdown` to "preview" changes when hovering/moving through the items (without committing the change via a click).
Example:
This is an opt-in feature, via a `<SelectDropdown isPreviewable />` prop.
The best part is the consumer doesn't have to tap into an alternative callback function for the preview function to work.
All of that is handled internally between a substate store and Downshift.
For fun, here's the state flow diagram I drew during the [Twitch stream](https://www.twitch.tv/videos/831237124) today when we were trying to figure this out.
Shout outs to @timothybjacobs for contributing ideas for this interaction!
Resolves https://github.com/ItsJonQ/g2/issues/182
> SelectDropdown: Add isPreviewable interaction

- packages/create-styles/src/create-style-system/create-core-element.js
run `yarn start`, open Storybook and ensure nothing is broken, especially in components that use forwarded refs like `TextInput`. Ensure refs of core elements are able to be retrieved (for eample in `TextInput` where we retrieve a ref of a `View` which is just the `div` core element).
> Remove automatic ref forwarding in core elements

- packages/components/src/select-dropdown/use-select-dropdown.js
This update fixes the unexpected duplicate onChange callback for the `SelectDropdown` component.
The solution was to add a guard for the `onChange` sync hook. This guard ensures that the `onChange` based on `value` changes only happens for `isPreviewable` mode.
Resolves: https://github.com/ItsJonQ/g2/issues/202
> SelectDropdown: Fix duplicate onChange callback

- packages/protokit/package.json
- packages/utils/package.json
- yarn.lock
This update bumps the [`use-enhanced-state`](https://github.com/ItsJonQ/use-enhanced-state) package to v0.0.13, which localizes the [`array-move`](https://www.npmjs.com/package/array-move) package. Hopefully, this helps with ECMA5 build for Gutenberg.
> Update to use-enhanced-state, localizing array-move for improved ES builds

- packages/components/src/select-dropdown/use-select-dropdown.js
This update ensures that the "select" (`button`) is focused after a selection action is made (either with mouse events or keyboard events).
The solution involved creating an internal `ref` for the `button` element, and (force) focusing that element within the `close` callback.
GIF above shows the Select element being focused (highlighted) after selecting an item.
Resolves https://github.com/ItsJonQ/g2/issues/208
> SelectDropdown: Focus "select" button on select action

- packages/components/src/font-size-control/__stories__/index.stories.js
- packages/components/src/font-size-control/use-font-size-control.js
The FontSizePicker had a renderItem prop. But that prop made the default unused:
https://github.com/ItsJonQ/g2/blob/3213c5991dd72c3ebe78eaa6d71e82beb3530ece/packages/components/src/font-size-control/font-size-control-select.js#L37-L40.
That happens because when spreading even if the prop is undefined we are overwriting the default. The current font size picker on component does not offer a renderItem component so I guess we can continue to not offer it https://github.com/ItsJonQ/g2/blob/3213c5991dd72c3ebe78eaa6d71e82beb3530ece/packages/components/src/font-size-control/font-size-control-select.js#L55
> Fix: Remove renderItem prop from font size picker

- packages/components/src/TextInput/__stories__/TextInput.stories.js
- packages/components/src/TextInput/useTextInputState.js
The sync action called when the value changes externally to synchronize the local state was making commitValue undefined.
We have this effect to call onChange when the value changes:
```
React.useEffect(() => {
return store.subscribe(
(value) => {
onChange(value);
},
(state) => state.commitValue,
shallowCompare,
);
}, [onChange, store]);
```
If the value updates externally, and then we delete the value, onChange is not called because in that case, commitValue does not change.
This PR fixes the issue by making sure commitValue is updated during the synchronization.
As an aside, it this a good practice to don't synchronize state:
https://kentcdodds.com/blog/dont-sync-state-derive-it
We rely a lot on state synchronization. I guess we should try to update our components to be less dependent …
> Fix: Text Input when value changes externally it becomes undeletable

- packages/components/src/font-size-control/__stories__/index.stories.js
- packages/components/src/font-size-control/font-size-control-utils.js
- packages/components/src/font-size-control/use-font-size-control.js
- packages/components/src/select-dropdown/use-select-dropdown.js
Currently, the FontSizePicker component makes an onChange call each time the component is rerendered.
The story I'm adding shows the issue in action.
This PR fixes the issue by making sure we are not generating new options on each rerender.
This PR fixes part of the end to end tests failures on https://github.com/WordPress/gutenberg/pull/27594.
Currently each time a block rerenders, the font size picker rerenders, and then we dispatch update block attribute actions.
I think that we also have an issue on the SelectDropdown component  (it is the one throwing onChange calls), but I did not manage to replicate this issue using that component in isolation after multiple tries where on each rerender I passed different objects.
I verified using the developer tools and the story I proposed that …
> Fix: Font size picker calls on change on each rerender.

- packages/components/src/UnitInput/UnitInput.utils.js
- packages/components/src/UnitInput/__stories__/UnitInput.stories.js
- packages/components/src/UnitInput/useUnitInput.js
This update fixes the handling of values like `auto` for `UnitInput`. Previously, `auto` may be assigned as a `unit` value.
This is because of the unit parsing function as it attempts to split `${number}${unit}` into `[value,unit]`. Since `auto` doesn't start with a number, the unit parser thinks that `auto` is the unit.
The solution was to add some validation for the initial store state, taking into consideration the `cssProp`, if provided.
> UnitInput: Improve initial unit parsing handling to better serve values like "auto"

- packages/components/src/UnitInput/UnitInput.utils.js
- packages/components/src/UnitInput/__stories__/UnitInput.stories.js
> UnitInput: Fix parsing of initial unit to handle `0` and unit values like `0px`

- packages/components/src/Accordion/useAccordion.js
- packages/components/src/TextInput/useTextInputState.js
- packages/components/src/TextInput/useTextInputState.utils.js
- packages/components/src/UnitInput/useUnitInput.js
- packages/context/src/context-system-provider.js
- packages/create-styles/src/components/theme-provider/utils.js
- packages/create-styles/src/hooks/use-reduced-motion.js
- packages/substate/package.json
- packages/substate/src/index.js
- packages/substate/src/use-sub-state.js
- packages/substate/src/zustand/README.md
- packages/substate/src/zustand/index.js
- packages/substate/src/zustand/middleware.js
- packages/substate/src/zustand/shallow.js
- packages/substate/src/zustand/types.ts
- packages/substate/src/zustand/vanilla.js
- yarn.lock
This update forks [zustand @3.3.1](https://github.com/pmndrs/zustand/releases/tag/v3.3.1) into `@wp-g2/substate` to make the library compatible with Gutenberg.
A big thanks to @saramarcondes for walking me through this update and teaching me how to **TYPE**!
> Fork Zustand (3.3.1) into @wp-g2/substate

- packages/context/src/__stories__/ComponentsProvider.stories.js
- packages/context/src/__tests__/__snapshots__/context-system-provider.test.js.snap
- packages/context/src/__tests__/context-system-provider.test.js
- packages/context/src/context-system-provider.js
- packages/context/src/use-context-system.js
This update refactors the ContextSystem to use default React hooks for config/render management rather than Zustand.
> Context System: Refactor substate

- package.json
- packages/components/package.json
- packages/create-styles/package.json
- packages/styles/package.json
- packages/styles/src/presets/get.js
- packages/utils/package.json
- packages/utils/src/index.js
- packages/utils/src/warning.js
- yarn.lock
While working on https://github.com/WordPress/gutenberg/pull/28280, I discovered that Gutenberg uses 2 different versions of Reakit library. This PR tries to resolve that issue. I also removed `reakit-warning` dependency in favor of `@wordpress/warning` that is nearly identical and authored by the same mastermind @diegohaz 😄 
I don't know why it was pinned to v1.1.0. Let's make sure we can use the latest version.
> Packages: Align reakit dependency with WordPress packages

- packages/components/src/Alert/__tests__/__snapshots__/Alert.test.js.snap
- packages/components/src/BaseButton/BaseButton.js
- packages/components/src/BaseButton/__tests__/__snapshots__/BaseButton.test.js.snap
- packages/components/src/Button/__tests__/__snapshots__/Button.test.js.snap
- packages/components/src/Card/__tests__/__snapshots__/Card.test.js.snap
- packages/components/src/ClipboardButton/__tests__/__snapshots__/ClipboardButton.test.js.snap
- packages/components/src/CloseButton/__tests__/__snapshots__/CloseButton.test.js.snap
- packages/components/src/Collapsible/__tests__/__snapshots__/Collapsible.test.js.snap
- packages/components/src/ColorControl/__tests__/__snapshots__/ColorControl.test.js.snap
- packages/components/src/ControlGroup/__tests__/__snapshots__/ControlGroup.test.js.snap
- packages/components/src/Popover/__tests__/__snapshots__/Popover.test.js.snap
- packages/components/src/SearchInput/__tests__/__snapshots__/SearchInput.test.js.snap
- packages/components/src/Stepper/__tests__/__snapshots__/Stepper.test.js.snap
- packages/components/src/Tag/__tests__/__snapshots__/Tag.test.js.snap
- packages/components/src/TextInput/types.ts
- packages/components/src/TextInput/useTextInput.js
- packages/components/src/TextInput/useTextInputState.js
- packages/components/src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
- packages/components/src/UnitInput/useUnitInput.js
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/components/src/select-dropdown/__tests__/__snapshots__/index.js.snap
- packages/components/src/select-dropdown/select-dropdown-styles.js
- packages/components/src/select-dropdown/select-dropdown.js
- packages/components/src/select-dropdown/use-select-dropdown.js
- yarn.lock
This update fixes the a11y voiceover handling for the `SelectDropdown` component, which powers components like the `FontSizePicker`.
This was discovered after the integration of the `FontSizePicker` into Gutenberg:
https://github.com/WordPress/gutenberg/pull/27594
The solution was the adjust the render structure for the `SelectDropdown` to better accommodate `useSelect()` from `downshift` (the same library/setup we use on the [`custom-select-control`](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/custom-select-control).
Unfortunately, we do lose the ability to `Portal` the menu content with this adjustment. It's more important that voiceover works correctly though.
We can revisit `useSelect` + portal'ing in the future.
From my experience, this doesn't seem …
> SelectDropdown: Fix some a11y voiceover issues

- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/components/src/select-dropdown/__tests__/__snapshots__/index.js.snap
- packages/components/src/select-dropdown/use-select-dropdown.js
This update fixes the `downshift` `useSelect` integration with `SelectDropdown`.
Previously, `aria-expanded` would only be added after an interaction with the dropdown.
We need the reference element (`button`) to have `aria-expanded` from it's initial render.
> SelectDropdown: Ensure initial aria-expanded is rendered in reference element

- packages/create-styles/package.json
- yarn.lock
This reverts commit d93cd4a709a446288a6340e035bf400aeb680992.
Create Styles: Update rtlcss to the latest v3 for PostCSS v8 #246
It looks like the updated version is having babel build issues with Gutenberg (the keyword `let`)
> Revert "Create Styles: Update rtlcss to the latest v3 for PostCSS v8

- packages/components/src/Flex/Flex.styles.js
- packages/components/src/Flex/useFlex.js
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/components/src/font-size-control/font-size-control-select.js
- packages/components/src/font-size-control/font-size-control-slider.js
- packages/components/src/font-size-control/font-size-control-styles.js
- packages/components/src/font-size-control/font-size-control-utils.js
This update improves Flex-based layout rendering for potentially longer translation labels.
This is achieved by enhancing how `Flex` handles `wrap` rendering. Previously, `Flex` only provided margin gaps on one axis (either `x` for horizontal, or `y` for vertical). With the updated `<Flex wrap />`, the `gap` value is now applied on both `x` and `y` to accommodate wrapped content.
This solution seems to work well. However, it involves quite a bit of manual CSS for the individual children of `HStack`.
The `FontSizeControl` how uses `HStack` instead of `Grid` for inner UI rendering. 
(Screenshot of Google translated German labels)
(Original English labels)
---
The changes made to this `FontSizeControl` need to be ported to Gutenberg.
We technically don't need to update `FontSizeControl` …
> Flex, HStack, FontSizePicker: Improve responsive rendering for longer translation labels

- packages/components/src/Accordion/Accordion.Context.js
- packages/components/src/Accordion/useAccordion.js
By moving action functions into module level functions we remove the need to memoize them. Their signature expands but not to the point of being unweildy.
Just an interesting approach to this problem, may or may not be something we adopt.
https://twitter.com/dan_abramov/status/1125774170154065920
> Remove need for memoization in accordion

- packages/components/src/ControlGroup/__tests__/__snapshots__/ControlGroup.test.js.snap
- packages/components/src/Select/__tests__/__snapshots__/Select.test.js.snap
- packages/components/src/Slider/__tests__/__snapshots__/Slider.test.js.snap
- packages/components/src/Subheading/__tests__/__snapshots__/Subheading.test.js.snap
- packages/components/src/Text/__tests__/__snapshots__/Text.test.js.snap
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/components/src/select-dropdown/__tests__/__snapshots__/index.js.snap
- packages/styles/src/theme/config.js
- packages/styles/src/theme/dark-mode-config.js
This update improves the contrast ratio of the `muted` variant for `Text` based components.
The value has been updated for both light and dark modes.
Resolves https://github.com/ItsJonQ/g2/issues/260
> Text: Improve muted contrast ratio

- packages/create-styles/src/components/theme-provider/theme-provider.js
- packages/create-styles/src/create-style-system/create-style-system.js
The wrapped ThemeProvider that `styles` exports should accept `compiler` or `globalStyles` as those are handled  by `createStyleSystem`.
> fix: Wrapped ThemeProvider props

- packages/context/src/context-connect.js
Previously the return type was passing through the whole of ViewOwnProps to PolymorphicComponent, but it should only take the props extracted from it. This PR fixes that.
> fix: contextConnect types

- packages/components/src/select-dropdown/select-dropdown-styles.js
This update removes the inline (JS) comment within the CSS string for `SelectDropdown`.
Resolves https://github.com/ItsJonQ/g2/issues/266
> SelectDropdown: Remove inline CSS comment

- packages/create-styles/src/create-compiler/__tests__/rtl.test.js
- packages/create-styles/src/create-compiler/plugins/rtl.js
Using `document.dir` instead of `document.getAttribute('dir')` for `rtl` checking
https://developer.mozilla.org/en-US/docs/Web/API/Document/dir
I didn't know about this 😍 
It's also much faster (tested with https://jsbench.me/)
Resolves: https://github.com/ItsJonQ/g2/issues/270
> RTL: Check document.dir on css() execution rather than using a cached value

- packages/context/src/context-connect.js
This simplifies the type and removes duplication of the `children` type which is problematic for elements like `hr` and `img` which do NOT have children.
Eventually we'll remove `children` from `ViewOwnProps` but that's a project for another day and will require a big refactor in the already ported component's types to explicitly annotate `children`. We should probably do this sooner than later though (probably this should be the first thing we do once these libraries exist in Gutenberg).
> Do not use ForwardRefRenderFuction

- packages/components/src/Alert/__tests__/__snapshots__/Alert.test.js.snap
- packages/components/src/BaseButton/__tests__/BaseButton.test.js
- packages/components/src/BaseButton/__tests__/__snapshots__/BaseButton.test.js.snap
- packages/components/src/BaseButton/useBaseButton.js
- packages/components/src/Button/__tests__/Button.test.js
- packages/components/src/Button/__tests__/__snapshots__/Button.test.js.snap
- packages/components/src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
- packages/components/src/Card/__tests__/__snapshots__/Card.test.js.snap
- packages/components/src/ClipboardButton/__tests__/__snapshots__/ClipboardButton.test.js.snap
- packages/components/src/CloseButton/__tests__/__snapshots__/CloseButton.test.js.snap
- packages/components/src/ColorControl/__tests__/__snapshots__/ColorControl.test.js.snap
- packages/components/src/ControlGroup/__tests__/__snapshots__/ControlGroup.test.js.snap
- packages/components/src/SearchInput/__tests__/__snapshots__/SearchInput.test.js.snap
- packages/components/src/Stepper/__tests__/__snapshots__/Stepper.test.js.snap
- packages/components/src/Tag/__tests__/__snapshots__/Tag.test.js.snap
- packages/components/src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
`<Button>` component should have `type="button"` by default, or else it will default to `type="submit"` when placing inside a `<form>` element. It's also the default value in gutenberg's `<Button>` component: https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/button/index.js#L77
Alternatively, we can enforce explicit `type` attribute with tools like [eslint](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md).
I ran into this problem when trying to place some components here inside a `<form>` element: https://github.com/WordPress/gutenberg/pull/29755#issuecomment-797426815. IMHO, this should be handled in the design system rather in the app level.
> Add type="button" by default to Button component

- packages/create-styles/src/create-compiler/README.md
- packages/create-styles/src/create-compiler/plugins/README.md
- packages/create-styles/src/create-style-system/README.md
> Add preliminary documentation to create-styles

- packages/components/src/TextInput/TextInputSteppers.js
- packages/components/src/__tests__/__snapshots__/Components.test.js.snap
- packages/components/src/select-dropdown/__tests__/__snapshots__/index.js.snap
- packages/components/src/select-dropdown/select-dropdown.js
Similar to #288, this PR adds `type="button"` to those components implicitly using `as="button"`. So that they won't be rendered as a submit button when placed inside a `<form>` element.
> Add `type="button"` to components using `as="button"` implicitly
